# Core agents for your personal workflow

- id: core.health_daily
  name: Health Daily
  enabled: true
  schedule: "0 8 * * *"  # for a future scheduler
  pipeline:
    - step: health_check
    - step: create_daily_note
      with:
        title: "Daily Health Check"

- id: core.notes_daily
  name: Notes Daily Stub
  enabled: true
  pipeline:
    - step: create_daily_note
      with:
        title: "Daily Note"
        content: "# Daily Note\n\n- Tasks:\n- Thoughts:\n"

- id: core.research_daily
  name: Research Daily
  enabled: true
  schedule: "0 9 * * *"
  inputs:
    queries: ["ai research", "vector databases"]
  filters:
    date_from: "2024-01-01"
  pipeline:
    - step: search_web
      with: { max_results: 5 }
    - step: filter_results
      with: { date_from: "@filters.date_from" }
    - step: save_index
    - step: save_sources_markdown
      with: { title: "Daily Research" }
    - step: ingest_qdrant
    - step: vector_topk
      with: { query: "ai research", k: 10, name: "research-topk" }

- id: core.transcription_inbox
  name: Transcription Inbox
  enabled: true
  pipeline:
    - step: transcribe_inbox
      with:
        inbox: "Inbox/Audio"

- id: core.transcription_daily
  name: Transcription Daily
  enabled: true
  schedule: "0 20 * * *"  # каждый день в 20:00
  pipeline:
    - step: transcribe_inbox_whisper
      with:
        inbox: "Inbox/Audio"
        model: "small"
        per_chunk_notes: true
        max_chars: 1800
        ingest: true

