services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/readyz"]
      interval: 10s
      timeout: 3s
      retries: 10
    profiles: ["qdrant", "all"]

  app:
    image: ghcr.io/koood8/vesna:v0.1.9
    environment:
      - AI_STACK_QDRANT_URL=http://qdrant:6333
      - AI_STACK_QDRANT_COLLECTION=ai_research
      - AI_STACK_EMB_MODEL=sentence-transformers/all-MiniLM-L6-v2
    volumes:
      - .:/app
    depends_on:
      qdrant:
        condition: service_healthy
    command: ["python3", "chat.py", "--health"]
    profiles: ["app", "all"]

volumes:
  qdrant_storage:

