name: docker-publish

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          flavor: |
            latest=false
            suffix=-lower,enable=true
          tags: |
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/heads/main') }}
            type=ref,event=tag

      - name: Normalize tags to lowercase
        id: norm
        run: |
          echo "tags=$(echo '${{ steps.meta.outputs.tags }}' | tr 'A-Z' 'a-z')" >> $GITHUB_OUTPUT
          echo "labels=$(echo '${{ steps.meta.outputs.labels }}' | tr 'A-Z' 'a-z')" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.norm.outputs.tags }}
          labels: ${{ steps.norm.outputs.labels }}

